### ISSUE TITLE
Error with division by zero with SDU

### ISSUE THREAD

**Issue by felselva** [spyros-lytras/dinuq#2]
Some times, the SDU metric won't work because `k` is zero in this section:

https://github.com/spyros-lytras/dinuq/blob/3bef82cf36f40c9e6f3a65722a592dde7e78de0c/dinuq/sdu.py#L467-L500

```
Traceback (most recent call last):
  File "dinuq_sdu.py", line 1225, in <module>
    ['pos1', 'pos2', 'bridge'])
  File "dinuq_sdu.py", line 566, in SDU
    sdu = sdu/k
```
Happens with `pos1`, `pos2` and/or `bridge`.

**Comment by spyros-lytras** [comment]
Hi!

Thanks for trying out the package and raising this issue! This is odd, because in this instance k should be the total number of amino acids in the sequence provided, so as long as the module can normally read the sequence then k should be more that 0 (equal to the length of the peptide sequence).

I would appreciate if you could send me one of the fasta files with which this error occurred, so I can do some testing and see what's going on! 

Many thanks,

Spyros

**Comment by spyros-lytras** [comment]
This problem was most likely caused by sequences not encoding for any of the amino acids informative for the calculations of interest. DinuQ v1.1.1 now instead of spitting out an error provides an 'NA' in the output of such cases (where k = 0) and proceeds to calculate any other values requested.
